# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2

updates:

  # NPM.
  - package-ecosystem: npm
    registries: "*"
    directory: "/"
    schedule:
      interval: daily
      time: "23:30"
      timezone: "Europe/London"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Upgraded"
      prefix-development: "Upgraded"
    ignore:
      - dependency-name: "svg-sprite"
