version: 2
updates:

  # NPM.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "02:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Upgraded]"
      prefix-development: "[Upgraded]"
