---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Vatu:   Dependabot Auto Merge
# Version 1.2.0
# Author: Michael Bragg <mike@vatu.co.uk>

name: "Dependabot Auto Merge"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:

  auto-merge:

    # Conditions for running workflow (project specific).
    if: >
      github.actor == 'dependabot[bot]'
    name: "Auto Merge"
    uses: vatu-team/workflows/.github/workflows/auto-merge-pr.yml@1.12.0
    with:
      runs-on: 'ubuntu-latest'
    secrets:
      BOT_ID: ${{ secrets.VATU_BOT_ID }}
      BOT_KEY: ${{ secrets.VATU_BOT_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_DEPENDABOT_TOKEN }}
